name: release

on:
  push:
    branches:
      - main
      - master
    tags:
      - "v*"
    pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: ./package.json
        name: Setup Node

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/drupal_meeting_parser-*.zip
          if-no-files-found: error
          overwrite: true

  release:
    if: github.ref_type == 'tag'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      -
        name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: dist
      -
        run: mkdir drupal_meeting_parser
      -
        run: unzip drupal_meeting_parser-*.zip -d drupal-meeting-parser
      -
        run: zip -r drupal_meeting_parser $('basename -s .zip drupal_meeting_parser-*.zip)-unpacked.zip
      -
        name: Create release
        uses: softprops/action-gh-release@v2.3.2
        with:
          files: "drupal_meeting_parser-*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

